### ISSUE TITLE
increase data density on the heap

### ISSUE THREAD

**Issue by jo-he** [owl-lisp/owl#85]
Currently, with a 64-bit VM, each immediate wastes four bytes (the 32 upper bits) on the heap. This could be improved in two ways:

1. **Introduce flexible-width fixnums**  
Immediates would be able to carry a value being word_size - 8 bits wide (with the current format). With this in place, big-num calculations could be faster, and take less memory on 64-bit systems.

2. **Store offsets instead of absolute pointers** (and use 32-bit words)  
Read and write each pointer through a macro, which optionally converts it to an offset (depending on the VM configuration). On the one hand this would add some overhead, but on the other hand offsets help the garbage collector when `realloc()` moves the memory. (And on x86_64 the binary size could be reduced a bit, when using more 32-bit instructions.) Offsets should be calculated from a fixed point (probably the start of the heap), so that `eq?` still works.

Whether the VM uses 32-bit or native-width words should be a compile time (or even run-time?) option, to serve different use cases. The same Owl byte-code should run on all VM variants.

**Comment by aoh** [comment]
The issue with flexible width bignums would be, that they could be immediates on one machine and allocated objects on another. Portability is a high priority, so I've trid to not go down this road.

Option 2 is exactly what should be done. A single root address for all memory access wouldn't add any extra cost to memory references, because although it would take an extra register for the root, a 32-bit word size would still leave several free 32-bit registers on x86_64. In addition, it would improve cache friendliness.

**Comment by aoh** [comment]
Closing, as development and issue tracking now happes at gitlab.com.
