### ISSUE TITLE
Undefined values when building on NetBSD

### ISSUE THREAD

**Issue by aoh** [owl-lisp/owl#87]
ENOTRECOVERABLE
EOWNERDEAD
CLOCK_PROCESS_CPUTIME_ID
CLOCK_THREAD_CPUTIME_ID

**Comment by jo-he** [comment]
The clock values will be fixed in NetBSD 8, which is already in RC1.
http://netbsd.gw.com/cgi-bin/man-cgi?clock_gettime++NetBSD-current

Unfortunately, `errno.h` was not updated within the five years, so we should definitely implement a workaround for them.
http://cvsweb.netbsd.org/bsdweb.cgi/src/sys/sys/errno.h?rev=1.40
